### ISSUE TITLE
There is an issue unrelated to the project

### ISSUE THREAD

**Issue by 516300502** [VictorHachard/odoo-modules#4]
![image](https://github.com/VictorHachard/odoo-modules/assets/37934050/c87ec203-4db0-4d51-86da-256feb3d0b4d)
Hi！I have defined an ir.actions.act_URL to redirect to other systems within odoo，But I need a login free operation，Do you know how to include identity authentication information, such as a token, in the request header when sending this request。I couldn't find any relevant information online。If you could give me some ideas, I would greatly appreciate it。

**Comment by VictorHachard** [comment]
Hi! 

You can define a Python method triggered by `ir.actions` and add an authentication token directly in the URL parameters or through custom HTTP headers. Reviewing Odoo’s integration methods, such as with Outlook, where OAuth is used, can also provide valuable insights into secure authentication for redirects.

**Comment by 516300502** [comment]
Thank you very much for your selfless help! Provided me with some ideas, I'll go take a look first.
